apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
spec:
  selector:
    matchLabels:
      app: springboot-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: registry.cn-shanghai.aliyuncs.com/zhangsiqiang/k8s-demo:v1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
spec:
#  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#      nodePort: 30000
  selector:
    app: springboot-demo

